sudo: false
dist: precise
language: java
matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk9
      dist: trusty
    - jdk: oraclejdk11
      dist: trusty

script: mvn clean verify -Dgpg.skip=true